# Generated by Django 4.1 on 2022-09-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='contenido',
            field=models.CharField(max_length=255, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
