# Generated by Django 4.1 on 2022-09-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='contenido',
            field=models.CharField(max_length=255, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
