# Generated by Django 4.1 on 2022-09-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publicaciones_contenido_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='id_categoria',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
