# Generated by Django 4.1 on 2022-09-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_publicaciones_id_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='resumen',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
