# Generated by Django 4.1 on 2022-09-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_publicaciones_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
